# Generated by Django 4.1.2 on 2023-07-19 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_randomapodtext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randomapodtext',
            old_name='message',
            new_name='explanation',
        ),
        migrations.RenameField(
            model_name='randomapodtext',
            old_name='link',
            new_name='url',
        ),
    ]
